spring:
  security:
    user:
      name: statistic
      password: statistic
      roles:
        - ADMIN
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      connection-timeout: 30000
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
    show-sql: true
    ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: statistics
server:
  port: 8081
app:
  services:
    sensors:
      url: ${SENSORS_API_URL}
      username: mr.admin
      password: sensoradmin
logging:
  level:
    org.springframework.core.env: DEBUG
