spring:
  security:
    user:
      name: statistic
      password: statistic
      roles:
        - ADMIN
  datasource:
    url: jdbc:postgresql://localhost:5432/statistics
    username: sa
    password: test
    hikari:
      connection-timeout: 30000
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
    show-sql: true
    ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: statistics
server:
  port: 8081
app:
  services:
    sensors:
      url: http://localhost:8080
      username: mr.admin
      password: sensoradmin
logging:
  level:
    org.springframework.core.env: DEBUG
